version: '3.8'
services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./php.ini:/usr/local/etc/php/php.ini
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
